apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: rs-news-dev-ns

resources:
- config.yaml
- gateway.yaml
- ./efs/pv-claim.yaml
- ../../loader
- ../../filter
- ../../portrait
- ../../rank
- ../../recall
- ../../redis
- ../../event
- ../../retrieve
- ../../demo
- ui

# all with following *kustomization*
images:
- name: rs/demo
  newName: 466154167985.dkr.ecr.ap-southeast-1.amazonaws.com/rs/demo
  newTag: 9553bff53313a2e6f1ba6971aba37a061c16b52b
- name: rs/event
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/event
  newTag: 86ef9dde80bcc5d94abd092567a72e9eea24259f
- name: rs/filter
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter
  newTag: 7a1145bcddd0a213781aac145dc671f0c8837ed6
- name: rs/filter-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter-plugin
  newTag: news-7a1145bcddd0a213781aac145dc671f0c8837ed6
- name: rs/loader
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/loader
  newTag: 5eaff51fb99b398b3efac1fa24b0ecaaffb7e220
- name: rs/portrait
  newName: public.ecr.aws/t8u1z3c8/rs/portrait
  newTag: latest
- name: rs/portrait-plugin
  newName: public.ecr.aws/t8u1z3c8/rs/portrait-plugin
  newTag: latest
- name: rs/rank
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/rank
  newTag: 5eaff51fb99b398b3efac1fa24b0ecaaffb7e220
- name: rs/rank-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/rank-plugin
  newTag: news-5eaff51fb99b398b3efac1fa24b0ecaaffb7e220
- name: rs/recall
  newName: 466154167985.dkr.ecr.ap-southeast-1.amazonaws.com/rs/recall
  newTag: da97ad60e7da5a313581a1fe430977b558664f65
- name: rs/recall-plugin
  newName: 466154167985.dkr.ecr.ap-southeast-1.amazonaws.com/rs/recall-plugin
  newTag: news-da97ad60e7da5a313581a1fe430977b558664f65
- name: rs/retrieve
  newName: 466154167985.dkr.ecr.ap-southeast-1.amazonaws.com/rs/retrieve
  newTag: 4f265597e91448fbcea2a6f2010e57c66791e066
- name: rs/ui
  newName: public.ecr.aws/t8u1z3c8/rs/ui
  newTag: latest



vars:
- fieldref:
    fieldPath: data.redis_host
  name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.redis_port
  name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_host
  name: MESSGE_BROKER_REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_port
  name: MESSGE_BROKER_REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.aws_region
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.s3_bucket
  name: S3_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.s3_prefix
  name: S3_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_bucket
  name: CLICK_RECORD_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_file_path
  name: CLICK_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.user_record_file_path
  name: USER_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.local_data_folder
  name: LOCAL_DATA_FOLDER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.method
  name: METHOD
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
