AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    (SO8010)

    CloudFormation for RecSys StepFuncs


Parameters:
  Stage:
    Type: String
    Default: dev

  StepFuncAndLambdaRoleName:
    Type: String
    Default: LambdaAndStepFuncsRole

  SagemakerRoleName:
    Type: String
    Default: SMRole

  S3UtilLabmda:
    Type: String
    Default: S3UtilLabmda

  PreCheckLabmda:
    Type: String
    Default: PreCheckLabmda

  SNSMessageLambda:
    Type: String
    Default: SNSMessageLambda

  CreateDatasetImportJobLambda:
    Type: String
    Default: CreateDatasetImportJobLambda

  UpdateSolutionVersionLambda:
    Type: String
    Default: UpdateSolutionVersionLambda

  UpdateCampaignLambda:
    Type: String
    Default: UpdateCampaignLambda

Resources:
  TrainModelStepFuncPersonalize:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/rs-${Stage}-${StepFuncAndLambdaRoleName}-${AWS::Region}"
      StateMachineName: !Sub rs-${Stage}-News-TrainModelStepFunc-Personalize
      DefinitionString: !Sub |
        {
          "StartAt": "Pre check",
          "TimeoutSeconds": 36000,
          "States": {
            "Pre check": {
              "Type": "Task",
              "Resource": "arn:${AWS::Partition}:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "rs-${Stage}-${PreCheckLabmda}",
                "Payload": {
                  "bucket.$": "$.Bucket",
                  "prefix.$": "$.S3Prefix",
                  "file_list": [
                    "system/personalize-data/personalize_interactions.csv"
                  ]
                }
              },
              "ResultSelector": {
                "Payload.$": "$.Payload"
              },
              "ResultPath": "$.Precheck",
              "Next": "Create Interaction Dataset Import Job"
            },
            "Create Interaction Dataset Import Job": {
              "Type": "Task",
              "Resource": "arn:${AWS::Partition}:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "rs-${Stage}-${CreateDatasetImportJobLambda}",
                "Payload": {
                  "bucket.$": "$.Bucket",
                  "prefix.$": "$.S3Prefix",
                  "datasetGroupName.$": "$.DatasetGroupName",
                  "datasetName.$": "$.DatasetName"
                },
              },
              "ResultSelector": {
                "Payload.$": "$.Payload"
              },
              "ResultPath": "$.CreateInteractionDatasetImportJob",
              "Next": "Update Solution Version"
            },
            "Update Solution Version": {
              "Type": "Task",
              "Resource": "arn:${AWS::Partition}:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "rs-${Stage}-${UpdateSolutionVersionLambda}",
                "Payload": {
                  "datasetGroupName.$": "$.DatasetGroupName",
                  "solutionName.$": "$.SolutionName",
                  "trainingMode.$": "$.TrainingMode"
                },
              },
              "ResultSelector": {
                "Payload.$": "$.Payload"
              },
              "ResultPath": "$.UpdateSolutionVersion",
              "Next": "Update Campaign"
            },
            "Update Campaign": {
              "Type": "Task",
              "Resource": "arn:${AWS::Partition}:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "rs-${Stage}-${UpdateCampaignLambda}",
                "Payload": {
                  "datasetGroupName.$": "$.DatasetGroupName",
                  "solutionName.$": "$.SolutionName",
                  "trainingMode.$": "$.TrainingMode"
                },
              },
              "ResultSelector": {
                "Payload.$": "$.Payload"
              },
              "ResultPath": "$.UpdateCampaign",
              "Next": "Succeed"
            },
            "Succeed": {
              "Type": "Succeed"
            }
          }
        }

