apiVersion: apps/v1
kind: Deployment 
metadata:
  name: retrieve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieve
  template:
    metadata:
      labels: 
        app: retrieve
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: rs-retrieve
        image:  rs/retrieve:latest
        ports:
          - name: http
            containerPort: 5600
        resources:
          requests: 
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
        env:
          - name: REDIS_HOST
            value: $(MESSGE_BROKER_REDIS_HOST)
          - name: REDIS_PORT
            value: $(MESSGE_BROKER_REDIS_PORT)
          - name: RETRIEVE_PORT
            value: "5600"
          - name: FILTER_HOST
            value: "filter"
          - name: FILTER_PORT
            value: "5200"
          - name: USE_PERSONALIZE_PLUGIN
            value: "True"
      - name: rs-retrieve-plugin
        image: rs/retrieve-plugin:latest
        ports:
          - name: http
            containerPort: 50051
        resources:
          requests:
            cpu: 2000m
            memory: 4096Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
        env:
          - name: LOCAL_DATA_FOLDER
            value: $(LOCAL_DATA_FOLDER)
          - name: AWS_REGION
            value: "ap-northeast-1"
          - name: PERSONALIZE_DATASET_GROUP
            value: "GCR-RS-News-Dataset-Group"
          - name: PERSONALIZE_SOLUTION
            value: "userPersonalizeSolutionNew"
          - name: PERSONALIZE_CAMPAIGN
            value: "gcr-rs-dev-workshop-news-UserPersonalize-campaign"
          - name: EVENT_TRACKER
            value: "NewsEventTracker"
          - name: REDIS_HOST
            value: $(REDIS_HOST)
          - name: REDIS_PORT
            value: $(REDIS_PORT)
        volumeMounts:
          - name: persistent-storage
            mountPath: /rs-data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
